# -*- coding: utf-8 -*-
"""ICC_WC_2003.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gS9o52VWLyEs17wNZiBHu8zQihZsn0uj
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %pylab inline
pylab.rcParams['figure.figsize'] = (15, 8)

"""# Top 10 ICC WC-2003

           *PLAYER*   **TEAM**  *M* *RUNS* *AVG*    *STK*  *4's*
1	Sachin Tendulkar  India	    11	673 	61.18	89.26	75	 4
2	Sourav Ganguly	India	    11	465	    58.12	82.30	30	 15
3	Ricky Ponting	Australia	10	415  	51.88	87.92	29	 13
4	Adam Gilchrist	Australia	10	408 	40.80	105.43	56	 7
5	Herschelle Gibbs SA	         6	384 	96.00	100.79	52   10
6	Marvan Atapattu	Sri Lanka	10	382 	54.57	84.51	50	 -
7	Andy Flower	    Zimbabwe    7	332 	47.43	72.33	30	 1
8	Matthew Hayden	Australia	11	328 	32.80	80.00	37	 5
9	Andrew Symonds	Australia	5	326   	163.00	90.56	32	 6
10	Damien Martyn	Australia	8	323 	64.60	81.77	21	 1
"""

playerList= ['Tendulkar','Ganguly','Ponting','Gilchrist','Gibbs','Atapattu','Andy','Hayden','Symonds','Martyn']
playerArray=np.array(playerList)
playerArray

print playerArray[0:6]
print playerArray[:7]
print playerArray[3:]
print playerArray[3:8]

runList=[673,465,415,408,384,382,332,328,326,323]
runArray=np.array(runList)
runArray

matchList=[11,11,10,10,6,10,7,11,5,8]
matchArray=np.array(matchList)
matchArray

avgList=[]
for x in range(len(matchArray)):
    avgList.append(runArray[x]/matchArray[x])
avgArray=np.array(avgList)
avgArray

dic={'player':playerArray,'match':matchArray,'runs':runArray,'avg':avgArray}
print dic

scoreCard=pd.DataFrame(dic, columns = ['player','match','runs','avg'])
scoreCard

scoreCard.describe()

sortedScore=scoreCard.sort_values(by=['runs'],ascending= False)
sortedScore.set_index("player",inplace = True)
sortedScore.plot.hist(alpha=0.7)
plt.show()
sortedScore.plot()
plt.show()

explode = [0.5,0.3,0.1,0.05,0.05,0.05,0.05,0.05,0.05,0.05]
fig1, ax1 = plt.subplots()
ax1.pie(scoreCard['runs'], explode=explode, labels=scoreCard['player'], autopct='%1.0f%%',
        shadow=True, startangle=90)
ax1.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.

plt.show()

